### ISSUE TITLE
Setup file error

### ISSUE THREAD

**Issue by Cr4ck3nCV** [deadbits/mimir#3]
Hi,

After trying to test this tool i've found several errors running setup.py install.

error: can't copy 'mimir/data/apikeys.json.example': doesn't exist or not a regular file
error: can't copy 'mimir/data/maxmind/*': doesn't exist or not a regular file
ValueError: bad marshal data (unknown type code)

**Comment by robben-ar** [comment]
I am having the same error.
What are the values ​​to configure the API?

> running install_data
error: can't copy 'mimir/data/apikeys.json.example': doesn't exist or not a regular file

**Comment by deadbits** [comment]
Hi folks, this project has been stalled for a while now unfortunately. The code just isnt at a usable point so you won't get any use out of this yet :( I appreciate the interest though!
